/*
 * HuggingFace Inference Provider API
 * Client for Hugging Face Chat Completions, Feature Extraction, and Text to Image APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mzattera.hfinferenceapi.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.mzattera.hfinferenceapi.client.model.AssistantMessageAllOfAudio;
import io.github.mzattera.hfinferenceapi.client.model.AssistantMessageAllOfContent;
import io.github.mzattera.hfinferenceapi.client.model.Message;
import io.github.mzattera.hfinferenceapi.client.model.ToolCall;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.xml.bind.annotation.*;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import io.github.mzattera.hfinferenceapi.JSON;

/**
 * AssistantMessage
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-14T22:22:52.426066200+01:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
@XmlRootElement(name = "AssistantMessage")
@XmlAccessorType(XmlAccessType.FIELD)

public class AssistantMessage extends Message {
  public static final String SERIALIZED_NAME_AUDIO = "audio";
  @XmlElement(name = "audio")
  @SerializedName(SERIALIZED_NAME_AUDIO)
  @javax.annotation.Nullable
  private AssistantMessageAllOfAudio audio;

  public static final String SERIALIZED_NAME_CONTENT = "content";
  @XmlElement(name = "content")
  @SerializedName(SERIALIZED_NAME_CONTENT)
  @javax.annotation.Nullable
  private AssistantMessageAllOfContent content;

  public static final String SERIALIZED_NAME_REASONING = "reasoning";
  @XmlElement(name = "reasoning")
  @SerializedName(SERIALIZED_NAME_REASONING)
  @javax.annotation.Nullable
  private String reasoning;

  public static final String SERIALIZED_NAME_NAME = "name";
  @XmlElement(name = "name")
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_REFUSAL = "refusal";
  @XmlElement(name = "refusal")
  @SerializedName(SERIALIZED_NAME_REFUSAL)
  @javax.annotation.Nullable
  private String refusal;

  public static final String SERIALIZED_NAME_TOOL_CALLS = "tool_calls";
  @XmlElement(name = "tool_calls")
  @SerializedName(SERIALIZED_NAME_TOOL_CALLS)
  @javax.annotation.Nullable
  private List<ToolCall> toolCalls = new ArrayList<>();

  public AssistantMessage() {

    this.role = RoleEnum.ASSISTANT;

  }

  public AssistantMessage audio(@javax.annotation.Nullable AssistantMessageAllOfAudio audio) {
    this.audio = audio;
    return this;
  }

  /**
   * Get audio
   * @return audio
   */
  @javax.annotation.Nullable
  public AssistantMessageAllOfAudio getAudio() {
    return audio;
  }

  public void setAudio(@javax.annotation.Nullable AssistantMessageAllOfAudio audio) {
    this.audio = audio;
  }


  public AssistantMessage content(@javax.annotation.Nullable AssistantMessageAllOfContent content) {
    this.content = content;
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @javax.annotation.Nullable
  public AssistantMessageAllOfContent getContent() {
    return content;
  }

  public void setContent(@javax.annotation.Nullable AssistantMessageAllOfContent content) {
    this.content = content;
  }


  public AssistantMessage reasoning(@javax.annotation.Nullable String reasoning) {
    this.reasoning = reasoning;
    return this;
  }

  /**
   * Get reasoning
   * @return reasoning
   */
  @javax.annotation.Nullable
  public String getReasoning() {
    return reasoning;
  }

  public void setReasoning(@javax.annotation.Nullable String reasoning) {
    this.reasoning = reasoning;
  }


  public AssistantMessage name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public AssistantMessage refusal(@javax.annotation.Nullable String refusal) {
    this.refusal = refusal;
    return this;
  }

  /**
   * The refusal message by the assistant
   * @return refusal
   */
  @javax.annotation.Nullable
  public String getRefusal() {
    return refusal;
  }

  public void setRefusal(@javax.annotation.Nullable String refusal) {
    this.refusal = refusal;
  }


  public AssistantMessage toolCalls(@javax.annotation.Nullable List<ToolCall> toolCalls) {
    this.toolCalls = toolCalls;
    return this;
  }

  public AssistantMessage addToolCallsItem(ToolCall toolCallsItem) {
    if (this.toolCalls == null) {
      this.toolCalls = new ArrayList<>();
    }
    this.toolCalls.add(toolCallsItem);
    return this;
  }

  /**
   * Get toolCalls
   * @return toolCalls
   */
  @javax.annotation.Nullable
  public List<ToolCall> getToolCalls() {
    return toolCalls;
  }

  public void setToolCalls(@javax.annotation.Nullable List<ToolCall> toolCalls) {
    this.toolCalls = toolCalls;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AssistantMessage instance itself
   */
  public AssistantMessage putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssistantMessage assistantMessage = (AssistantMessage) o;
    return Objects.equals(this.audio, assistantMessage.audio) &&
        Objects.equals(this.content, assistantMessage.content) &&
        Objects.equals(this.reasoning, assistantMessage.reasoning) &&
        Objects.equals(this.name, assistantMessage.name) &&
        Objects.equals(this.refusal, assistantMessage.refusal) &&
        Objects.equals(this.toolCalls, assistantMessage.toolCalls)&&
        Objects.equals(this.additionalProperties, assistantMessage.additionalProperties) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(audio, content, reasoning, name, refusal, toolCalls, super.hashCode(), additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssistantMessage {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    audio: ").append(toIndentedString(audio)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    reasoning: ").append(toIndentedString(reasoning)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    refusal: ").append(toIndentedString(refusal)).append("\n");
    sb.append("    toolCalls: ").append(toIndentedString(toolCalls)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("role", "audio", "content", "reasoning", "name", "refusal", "tool_calls"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("role"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AssistantMessage
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AssistantMessage.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in AssistantMessage is not found in the empty JSON string", AssistantMessage.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AssistantMessage.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AssistantMessage.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AssistantMessage' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AssistantMessage> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AssistantMessage.class));

       return (TypeAdapter<T>) new TypeAdapter<AssistantMessage>() {
           @Override
           public void write(JsonWriter out, AssistantMessage value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AssistantMessage read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             AssistantMessage instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AssistantMessage given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AssistantMessage
   * @throws IOException if the JSON string is invalid with respect to AssistantMessage
   */
  public static AssistantMessage fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AssistantMessage.class);
  }

  /**
   * Convert an instance of AssistantMessage to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

