/*
 * HuggingFace Inference Provider API
 * Client for Hugging Face Chat Completions, Feature Extraction, and Text to Image APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mzattera.hfinferenceapi.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.mzattera.hfinferenceapi.client.model.ChatCompletionRequestResponseFormatOneOf;
import io.github.mzattera.hfinferenceapi.client.model.ChatCompletionRequestResponseFormatOneOf1;
import java.io.IOException;
import java.util.Arrays;
import javax.xml.bind.annotation.*;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Locale;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import io.github.mzattera.hfinferenceapi.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-07T16:58:05.267507900+01:00[Europe/Rome]", comments = "Generator version: 7.17.0")
@XmlRootElement(name = "ChatCompletionRequestResponseFormat")
@XmlAccessorType(XmlAccessType.FIELD)

public class ChatCompletionRequestResponseFormat extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(ChatCompletionRequestResponseFormat.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ChatCompletionRequestResponseFormat.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ChatCompletionRequestResponseFormat' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ChatCompletionRequestResponseFormatOneOf> adapterChatCompletionRequestResponseFormatOneOf = gson.getDelegateAdapter(this, TypeToken.get(ChatCompletionRequestResponseFormatOneOf.class));
            final TypeAdapter<ChatCompletionRequestResponseFormatOneOf1> adapterChatCompletionRequestResponseFormatOneOf1 = gson.getDelegateAdapter(this, TypeToken.get(ChatCompletionRequestResponseFormatOneOf1.class));

            return (TypeAdapter<T>) new TypeAdapter<ChatCompletionRequestResponseFormat>() {
                @Override
                public void write(JsonWriter out, ChatCompletionRequestResponseFormat value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `ChatCompletionRequestResponseFormatOneOf`
                    if (value.getActualInstance() instanceof ChatCompletionRequestResponseFormatOneOf) {
                        JsonElement element = adapterChatCompletionRequestResponseFormatOneOf.toJsonTree((ChatCompletionRequestResponseFormatOneOf)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `ChatCompletionRequestResponseFormatOneOf1`
                    if (value.getActualInstance() instanceof ChatCompletionRequestResponseFormatOneOf1) {
                        JsonElement element = adapterChatCompletionRequestResponseFormatOneOf1.toJsonTree((ChatCompletionRequestResponseFormatOneOf1)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: ChatCompletionRequestResponseFormatOneOf, ChatCompletionRequestResponseFormatOneOf1");
                }

                @Override
                public ChatCompletionRequestResponseFormat read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize ChatCompletionRequestResponseFormatOneOf
                    try {
                        // validate the JSON object to see if any exception is thrown
                        ChatCompletionRequestResponseFormatOneOf.validateJsonElement(jsonElement);
                        actualAdapter = adapterChatCompletionRequestResponseFormatOneOf;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'ChatCompletionRequestResponseFormatOneOf'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(Locale.ROOT, "Deserialization for ChatCompletionRequestResponseFormatOneOf failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'ChatCompletionRequestResponseFormatOneOf'", e);
                    }
                    // deserialize ChatCompletionRequestResponseFormatOneOf1
                    try {
                        // validate the JSON object to see if any exception is thrown
                        ChatCompletionRequestResponseFormatOneOf1.validateJsonElement(jsonElement);
                        actualAdapter = adapterChatCompletionRequestResponseFormatOneOf1;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'ChatCompletionRequestResponseFormatOneOf1'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(Locale.ROOT, "Deserialization for ChatCompletionRequestResponseFormatOneOf1 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'ChatCompletionRequestResponseFormatOneOf1'", e);
                    }

                    if (match == 1) {
                        ChatCompletionRequestResponseFormat ret = new ChatCompletionRequestResponseFormat();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format(Locale.ROOT, "Failed deserialization for ChatCompletionRequestResponseFormat: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public ChatCompletionRequestResponseFormat() {
        super("oneOf", Boolean.FALSE);
    }

    public ChatCompletionRequestResponseFormat(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("ChatCompletionRequestResponseFormatOneOf", ChatCompletionRequestResponseFormatOneOf.class);
        schemas.put("ChatCompletionRequestResponseFormatOneOf1", ChatCompletionRequestResponseFormatOneOf1.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return ChatCompletionRequestResponseFormat.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * ChatCompletionRequestResponseFormatOneOf, ChatCompletionRequestResponseFormatOneOf1
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof ChatCompletionRequestResponseFormatOneOf) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof ChatCompletionRequestResponseFormatOneOf1) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be ChatCompletionRequestResponseFormatOneOf, ChatCompletionRequestResponseFormatOneOf1");
    }

    /**
     * Get the actual instance, which can be the following:
     * ChatCompletionRequestResponseFormatOneOf, ChatCompletionRequestResponseFormatOneOf1
     *
     * @return The actual instance (ChatCompletionRequestResponseFormatOneOf, ChatCompletionRequestResponseFormatOneOf1)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `ChatCompletionRequestResponseFormatOneOf`. If the actual instance is not `ChatCompletionRequestResponseFormatOneOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `ChatCompletionRequestResponseFormatOneOf`
     * @throws ClassCastException if the instance is not `ChatCompletionRequestResponseFormatOneOf`
     */
    public ChatCompletionRequestResponseFormatOneOf getChatCompletionRequestResponseFormatOneOf() throws ClassCastException {
        return (ChatCompletionRequestResponseFormatOneOf)super.getActualInstance();
    }

    /**
     * Get the actual instance of `ChatCompletionRequestResponseFormatOneOf1`. If the actual instance is not `ChatCompletionRequestResponseFormatOneOf1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `ChatCompletionRequestResponseFormatOneOf1`
     * @throws ClassCastException if the instance is not `ChatCompletionRequestResponseFormatOneOf1`
     */
    public ChatCompletionRequestResponseFormatOneOf1 getChatCompletionRequestResponseFormatOneOf1() throws ClassCastException {
        return (ChatCompletionRequestResponseFormatOneOf1)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to ChatCompletionRequestResponseFormat
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with ChatCompletionRequestResponseFormatOneOf
        try {
            ChatCompletionRequestResponseFormatOneOf.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format(Locale.ROOT, "Deserialization for ChatCompletionRequestResponseFormatOneOf failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with ChatCompletionRequestResponseFormatOneOf1
        try {
            ChatCompletionRequestResponseFormatOneOf1.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format(Locale.ROOT, "Deserialization for ChatCompletionRequestResponseFormatOneOf1 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format(Locale.ROOT, "The JSON string is invalid for ChatCompletionRequestResponseFormat with oneOf schemas: ChatCompletionRequestResponseFormatOneOf, ChatCompletionRequestResponseFormatOneOf1. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of ChatCompletionRequestResponseFormat given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of ChatCompletionRequestResponseFormat
     * @throws IOException if the JSON string is invalid with respect to ChatCompletionRequestResponseFormat
     */
    public static ChatCompletionRequestResponseFormat fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, ChatCompletionRequestResponseFormat.class);
    }

    /**
     * Convert an instance of ChatCompletionRequestResponseFormat to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

