/*
 * HuggingFace Inference Provider API
 * API for GenAI services: image generation, chat completions, embeddings
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mzattera.hfinferenceapi.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.mzattera.hfinferenceapi.client.model.ChatCompletionResponseXGroq;
import io.github.mzattera.hfinferenceapi.client.model.Choice;
import io.github.mzattera.hfinferenceapi.client.model.Usage;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.xml.bind.annotation.*;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import io.github.mzattera.hfinferenceapi.JSON;

/**
 * ChatCompletionResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-04T08:01:40.423980900+01:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
@XmlRootElement(name = "ChatCompletionResponse")
@XmlAccessorType(XmlAccessType.FIELD)

public class ChatCompletionResponse {
  public static final String SERIALIZED_NAME_OBJECT = "object";
  @XmlElement(name = "object")
  @SerializedName(SERIALIZED_NAME_OBJECT)
  @javax.annotation.Nullable
  private String _object;

  public static final String SERIALIZED_NAME_CHOICES = "choices";
  @XmlElement(name = "choices")
  @SerializedName(SERIALIZED_NAME_CHOICES)
  @javax.annotation.Nullable
  private List<Choice> choices = new ArrayList<>();

  public static final String SERIALIZED_NAME_CREATED = "created";
  @XmlElement(name = "created")
  @SerializedName(SERIALIZED_NAME_CREATED)
  @javax.annotation.Nullable
  private Integer created;

  public static final String SERIALIZED_NAME_ID = "id";
  @XmlElement(name = "id")
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_MODEL = "model";
  @XmlElement(name = "model")
  @SerializedName(SERIALIZED_NAME_MODEL)
  @javax.annotation.Nullable
  private String model;

  public static final String SERIALIZED_NAME_USAGE_BREAKDOWN = "usage_breakdown";
  @XmlElement(name = "usage_breakdown")
  @SerializedName(SERIALIZED_NAME_USAGE_BREAKDOWN)
  @javax.annotation.Nullable
  private Object usageBreakdown;

  public static final String SERIALIZED_NAME_SYSTEM_FINGERPRINT = "system_fingerprint";
  @XmlElement(name = "system_fingerprint")
  @SerializedName(SERIALIZED_NAME_SYSTEM_FINGERPRINT)
  @javax.annotation.Nullable
  private String systemFingerprint;

  public static final String SERIALIZED_NAME_SERVICE_TIER = "service_tier";
  @XmlElement(name = "service_tier")
  @SerializedName(SERIALIZED_NAME_SERVICE_TIER)
  @javax.annotation.Nullable
  private String serviceTier;

  public static final String SERIALIZED_NAME_X_GROQ = "x_groq";
  @XmlElement(name = "x_groq")
  @SerializedName(SERIALIZED_NAME_X_GROQ)
  @javax.annotation.Nullable
  private ChatCompletionResponseXGroq xGroq;

  public static final String SERIALIZED_NAME_USAGE = "usage";
  @XmlElement(name = "usage")
  @SerializedName(SERIALIZED_NAME_USAGE)
  @javax.annotation.Nullable
  private Usage usage;

  public ChatCompletionResponse() {
  }

  public ChatCompletionResponse _object(@javax.annotation.Nullable String _object) {
    this._object = _object;
    return this;
  }

  /**
   * Get _object
   * @return _object
   */
  @javax.annotation.Nullable
  public String getObject() {
    return _object;
  }

  public void setObject(@javax.annotation.Nullable String _object) {
    this._object = _object;
  }


  public ChatCompletionResponse choices(@javax.annotation.Nullable List<Choice> choices) {
    this.choices = choices;
    return this;
  }

  public ChatCompletionResponse addChoicesItem(Choice choicesItem) {
    if (this.choices == null) {
      this.choices = new ArrayList<>();
    }
    this.choices.add(choicesItem);
    return this;
  }

  /**
   * Get choices
   * @return choices
   */
  @javax.annotation.Nullable
  public List<Choice> getChoices() {
    return choices;
  }

  public void setChoices(@javax.annotation.Nullable List<Choice> choices) {
    this.choices = choices;
  }


  public ChatCompletionResponse created(@javax.annotation.Nullable Integer created) {
    this.created = created;
    return this;
  }

  /**
   * Get created
   * @return created
   */
  @javax.annotation.Nullable
  public Integer getCreated() {
    return created;
  }

  public void setCreated(@javax.annotation.Nullable Integer created) {
    this.created = created;
  }


  public ChatCompletionResponse id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public ChatCompletionResponse model(@javax.annotation.Nullable String model) {
    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @javax.annotation.Nullable
  public String getModel() {
    return model;
  }

  public void setModel(@javax.annotation.Nullable String model) {
    this.model = model;
  }


  public ChatCompletionResponse usageBreakdown(@javax.annotation.Nullable Object usageBreakdown) {
    this.usageBreakdown = usageBreakdown;
    return this;
  }

  /**
   * Get usageBreakdown
   * @return usageBreakdown
   */
  @javax.annotation.Nullable
  public Object getUsageBreakdown() {
    return usageBreakdown;
  }

  public void setUsageBreakdown(@javax.annotation.Nullable Object usageBreakdown) {
    this.usageBreakdown = usageBreakdown;
  }


  public ChatCompletionResponse systemFingerprint(@javax.annotation.Nullable String systemFingerprint) {
    this.systemFingerprint = systemFingerprint;
    return this;
  }

  /**
   * Get systemFingerprint
   * @return systemFingerprint
   */
  @javax.annotation.Nullable
  public String getSystemFingerprint() {
    return systemFingerprint;
  }

  public void setSystemFingerprint(@javax.annotation.Nullable String systemFingerprint) {
    this.systemFingerprint = systemFingerprint;
  }


  public ChatCompletionResponse serviceTier(@javax.annotation.Nullable String serviceTier) {
    this.serviceTier = serviceTier;
    return this;
  }

  /**
   * Get serviceTier
   * @return serviceTier
   */
  @javax.annotation.Nullable
  public String getServiceTier() {
    return serviceTier;
  }

  public void setServiceTier(@javax.annotation.Nullable String serviceTier) {
    this.serviceTier = serviceTier;
  }


  public ChatCompletionResponse xGroq(@javax.annotation.Nullable ChatCompletionResponseXGroq xGroq) {
    this.xGroq = xGroq;
    return this;
  }

  /**
   * Get xGroq
   * @return xGroq
   */
  @javax.annotation.Nullable
  public ChatCompletionResponseXGroq getxGroq() {
    return xGroq;
  }

  public void setxGroq(@javax.annotation.Nullable ChatCompletionResponseXGroq xGroq) {
    this.xGroq = xGroq;
  }


  public ChatCompletionResponse usage(@javax.annotation.Nullable Usage usage) {
    this.usage = usage;
    return this;
  }

  /**
   * Get usage
   * @return usage
   */
  @javax.annotation.Nullable
  public Usage getUsage() {
    return usage;
  }

  public void setUsage(@javax.annotation.Nullable Usage usage) {
    this.usage = usage;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatCompletionResponse chatCompletionResponse = (ChatCompletionResponse) o;
    return Objects.equals(this._object, chatCompletionResponse._object) &&
        Objects.equals(this.choices, chatCompletionResponse.choices) &&
        Objects.equals(this.created, chatCompletionResponse.created) &&
        Objects.equals(this.id, chatCompletionResponse.id) &&
        Objects.equals(this.model, chatCompletionResponse.model) &&
        Objects.equals(this.usageBreakdown, chatCompletionResponse.usageBreakdown) &&
        Objects.equals(this.systemFingerprint, chatCompletionResponse.systemFingerprint) &&
        Objects.equals(this.serviceTier, chatCompletionResponse.serviceTier) &&
        Objects.equals(this.xGroq, chatCompletionResponse.xGroq) &&
        Objects.equals(this.usage, chatCompletionResponse.usage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_object, choices, created, id, model, usageBreakdown, systemFingerprint, serviceTier, xGroq, usage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatCompletionResponse {\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    choices: ").append(toIndentedString(choices)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    usageBreakdown: ").append(toIndentedString(usageBreakdown)).append("\n");
    sb.append("    systemFingerprint: ").append(toIndentedString(systemFingerprint)).append("\n");
    sb.append("    serviceTier: ").append(toIndentedString(serviceTier)).append("\n");
    sb.append("    xGroq: ").append(toIndentedString(xGroq)).append("\n");
    sb.append("    usage: ").append(toIndentedString(usage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("object", "choices", "created", "id", "model", "usage_breakdown", "system_fingerprint", "service_tier", "x_groq", "usage"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ChatCompletionResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ChatCompletionResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in ChatCompletionResponse is not found in the empty JSON string", ChatCompletionResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ChatCompletionResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ChatCompletionResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("object") != null && !jsonObj.get("object").isJsonNull()) && !jsonObj.get("object").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `object` to be a primitive type in the JSON string but got `%s`", jsonObj.get("object").toString()));
      }
      if (jsonObj.get("choices") != null && !jsonObj.get("choices").isJsonNull()) {
        JsonArray jsonArraychoices = jsonObj.getAsJsonArray("choices");
        if (jsonArraychoices != null) {
          // ensure the json data is an array
          if (!jsonObj.get("choices").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `choices` to be an array in the JSON string but got `%s`", jsonObj.get("choices").toString()));
          }

          // validate the optional field `choices` (array)
          for (int i = 0; i < jsonArraychoices.size(); i++) {
            Choice.validateJsonElement(jsonArraychoices.get(i));
          };
        }
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("model") != null && !jsonObj.get("model").isJsonNull()) && !jsonObj.get("model").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `model` to be a primitive type in the JSON string but got `%s`", jsonObj.get("model").toString()));
      }
      if ((jsonObj.get("system_fingerprint") != null && !jsonObj.get("system_fingerprint").isJsonNull()) && !jsonObj.get("system_fingerprint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `system_fingerprint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("system_fingerprint").toString()));
      }
      if ((jsonObj.get("service_tier") != null && !jsonObj.get("service_tier").isJsonNull()) && !jsonObj.get("service_tier").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `service_tier` to be a primitive type in the JSON string but got `%s`", jsonObj.get("service_tier").toString()));
      }
      // validate the optional field `x_groq`
      if (jsonObj.get("x_groq") != null && !jsonObj.get("x_groq").isJsonNull()) {
        ChatCompletionResponseXGroq.validateJsonElement(jsonObj.get("x_groq"));
      }
      // validate the optional field `usage`
      if (jsonObj.get("usage") != null && !jsonObj.get("usage").isJsonNull()) {
        Usage.validateJsonElement(jsonObj.get("usage"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ChatCompletionResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ChatCompletionResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ChatCompletionResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ChatCompletionResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ChatCompletionResponse>() {
           @Override
           public void write(JsonWriter out, ChatCompletionResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ChatCompletionResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ChatCompletionResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ChatCompletionResponse
   * @throws IOException if the JSON string is invalid with respect to ChatCompletionResponse
   */
  public static ChatCompletionResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ChatCompletionResponse.class);
  }

  /**
   * Convert an instance of ChatCompletionResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

