/*
 * HuggingFace Inference Provider API
 * Client for Hugging Face Chat Completions, Feature Extraction, and Text to Image APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mzattera.hfinferenceapi.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.xml.bind.annotation.*;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import io.github.mzattera.hfinferenceapi.JSON;

/**
 * EmbeddingsRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-08T08:22:32.908358200+01:00[Europe/Rome]", comments = "Generator version: 7.17.0")
@XmlRootElement(name = "EmbeddingsRequest")
@XmlAccessorType(XmlAccessType.FIELD)

public class EmbeddingsRequest {
  public static final String SERIALIZED_NAME_MODEL = "model";
  @XmlElement(name = "model")
  @SerializedName(SERIALIZED_NAME_MODEL)
  @javax.annotation.Nonnull
  private String model;

  public static final String SERIALIZED_NAME_INPUT = "input";
  @XmlElement(name = "input")
  @SerializedName(SERIALIZED_NAME_INPUT)
  @javax.annotation.Nonnull
  private List<String> input = new ArrayList<>();

  public static final String SERIALIZED_NAME_NORMALIZE = "normalize";
  @XmlElement(name = "normalize")
  @SerializedName(SERIALIZED_NAME_NORMALIZE)
  @javax.annotation.Nullable
  private Boolean normalize;

  public static final String SERIALIZED_NAME_PROMPT_NAME = "prompt_name";
  @XmlElement(name = "prompt_name")
  @SerializedName(SERIALIZED_NAME_PROMPT_NAME)
  @javax.annotation.Nullable
  private String promptName;

  public static final String SERIALIZED_NAME_TRUNCATE = "truncate";
  @XmlElement(name = "truncate")
  @SerializedName(SERIALIZED_NAME_TRUNCATE)
  @javax.annotation.Nullable
  private Boolean truncate;

  /**
   * Gets or Sets truncationDirection
   */
  @JsonAdapter(TruncationDirectionEnum.Adapter.class)
  @XmlType(name="TruncationDirectionEnum")
  @XmlEnum(String.class)
  public enum TruncationDirectionEnum {
    @XmlEnumValue("left")
    LEFT("left"),
    
    @XmlEnumValue("right")
    RIGHT("right");

    private String value;

    TruncationDirectionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TruncationDirectionEnum fromValue(String value) {
      for (TruncationDirectionEnum b : TruncationDirectionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TruncationDirectionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TruncationDirectionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TruncationDirectionEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TruncationDirectionEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TruncationDirectionEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TRUNCATION_DIRECTION = "truncation_direction";
  @XmlElement(name = "truncation_direction")
  @SerializedName(SERIALIZED_NAME_TRUNCATION_DIRECTION)
  @javax.annotation.Nullable
  private TruncationDirectionEnum truncationDirection;

  public EmbeddingsRequest() {
  }

  public EmbeddingsRequest model(@javax.annotation.Nonnull String model) {
    this.model = model;
    return this;
  }

  /**
   * Model to use.
   * @return model
   */
  @javax.annotation.Nonnull
  public String getModel() {
    return model;
  }

  public void setModel(@javax.annotation.Nonnull String model) {
    this.model = model;
  }


  public EmbeddingsRequest input(@javax.annotation.Nonnull List<String> input) {
    this.input = input;
    return this;
  }

  public EmbeddingsRequest addInputItem(String inputItem) {
    if (this.input == null) {
      this.input = new ArrayList<>();
    }
    this.input.add(inputItem);
    return this;
  }

  /**
   * Array of strings with inputs.
   * @return input
   */
  @javax.annotation.Nonnull
  public List<String> getInput() {
    return input;
  }

  public void setInput(@javax.annotation.Nonnull List<String> input) {
    this.input = input;
  }


  public EmbeddingsRequest normalize(@javax.annotation.Nullable Boolean normalize) {
    this.normalize = normalize;
    return this;
  }

  /**
   * If true, normalize embeddings.
   * @return normalize
   */
  @javax.annotation.Nullable
  public Boolean getNormalize() {
    return normalize;
  }

  public void setNormalize(@javax.annotation.Nullable Boolean normalize) {
    this.normalize = normalize;
  }


  public EmbeddingsRequest promptName(@javax.annotation.Nullable String promptName) {
    this.promptName = promptName;
    return this;
  }

  /**
   * The name of the prompt that should be used for encoding.
   * @return promptName
   */
  @javax.annotation.Nullable
  public String getPromptName() {
    return promptName;
  }

  public void setPromptName(@javax.annotation.Nullable String promptName) {
    this.promptName = promptName;
  }


  public EmbeddingsRequest truncate(@javax.annotation.Nullable Boolean truncate) {
    this.truncate = truncate;
    return this;
  }

  /**
   * Whether to truncate inputs
   * @return truncate
   */
  @javax.annotation.Nullable
  public Boolean getTruncate() {
    return truncate;
  }

  public void setTruncate(@javax.annotation.Nullable Boolean truncate) {
    this.truncate = truncate;
  }


  public EmbeddingsRequest truncationDirection(@javax.annotation.Nullable TruncationDirectionEnum truncationDirection) {
    this.truncationDirection = truncationDirection;
    return this;
  }

  /**
   * Get truncationDirection
   * @return truncationDirection
   */
  @javax.annotation.Nullable
  public TruncationDirectionEnum getTruncationDirection() {
    return truncationDirection;
  }

  public void setTruncationDirection(@javax.annotation.Nullable TruncationDirectionEnum truncationDirection) {
    this.truncationDirection = truncationDirection;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmbeddingsRequest embeddingsRequest = (EmbeddingsRequest) o;
    return Objects.equals(this.model, embeddingsRequest.model) &&
        Objects.equals(this.input, embeddingsRequest.input) &&
        Objects.equals(this.normalize, embeddingsRequest.normalize) &&
        Objects.equals(this.promptName, embeddingsRequest.promptName) &&
        Objects.equals(this.truncate, embeddingsRequest.truncate) &&
        Objects.equals(this.truncationDirection, embeddingsRequest.truncationDirection);
  }

  @Override
  public int hashCode() {
    return Objects.hash(model, input, normalize, promptName, truncate, truncationDirection);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmbeddingsRequest {\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    input: ").append(toIndentedString(input)).append("\n");
    sb.append("    normalize: ").append(toIndentedString(normalize)).append("\n");
    sb.append("    promptName: ").append(toIndentedString(promptName)).append("\n");
    sb.append("    truncate: ").append(toIndentedString(truncate)).append("\n");
    sb.append("    truncationDirection: ").append(toIndentedString(truncationDirection)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("model", "input", "normalize", "prompt_name", "truncate", "truncation_direction"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("model", "input"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EmbeddingsRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EmbeddingsRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in EmbeddingsRequest is not found in the empty JSON string", EmbeddingsRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EmbeddingsRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `EmbeddingsRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : EmbeddingsRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("model").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `model` to be a primitive type in the JSON string but got `%s`", jsonObj.get("model").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("input") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("input").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `input` to be an array in the JSON string but got `%s`", jsonObj.get("input").toString()));
      }
      if ((jsonObj.get("prompt_name") != null && !jsonObj.get("prompt_name").isJsonNull()) && !jsonObj.get("prompt_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `prompt_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("prompt_name").toString()));
      }
      if ((jsonObj.get("truncation_direction") != null && !jsonObj.get("truncation_direction").isJsonNull()) && !jsonObj.get("truncation_direction").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `truncation_direction` to be a primitive type in the JSON string but got `%s`", jsonObj.get("truncation_direction").toString()));
      }
      // validate the optional field `truncation_direction`
      if (jsonObj.get("truncation_direction") != null && !jsonObj.get("truncation_direction").isJsonNull()) {
        TruncationDirectionEnum.validateJsonElement(jsonObj.get("truncation_direction"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EmbeddingsRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EmbeddingsRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EmbeddingsRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EmbeddingsRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<EmbeddingsRequest>() {
           @Override
           public void write(JsonWriter out, EmbeddingsRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EmbeddingsRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EmbeddingsRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EmbeddingsRequest
   * @throws IOException if the JSON string is invalid with respect to EmbeddingsRequest
   */
  public static EmbeddingsRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EmbeddingsRequest.class);
  }

  /**
   * Convert an instance of EmbeddingsRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

