/*
 * HuggingFace Inference Provider API
 * Client for Hugging Face Chat Completions, Feature Extraction, and Text to Image APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mzattera.hfinferenceapi.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import javax.xml.bind.annotation.*;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import io.github.mzattera.hfinferenceapi.JSON;

/**
 * FileContentPartAllOfFile
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-14T13:04:21.768158100+01:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
@XmlRootElement(name = "FileContentPartAllOfFile")
@XmlAccessorType(XmlAccessType.FIELD)

public class FileContentPartAllOfFile {
  public static final String SERIALIZED_NAME_FILE_DATA = "file_data";
  @XmlElement(name = "file_data")
  @SerializedName(SERIALIZED_NAME_FILE_DATA)
  @javax.annotation.Nullable
  private String fileData;

  public static final String SERIALIZED_NAME_FILE_ID = "file_id";
  @XmlElement(name = "file_id")
  @SerializedName(SERIALIZED_NAME_FILE_ID)
  @javax.annotation.Nullable
  private String fileId;

  public static final String SERIALIZED_NAME_FILENAME = "filename";
  @XmlElement(name = "filename")
  @SerializedName(SERIALIZED_NAME_FILENAME)
  @javax.annotation.Nullable
  private String filename;

  public FileContentPartAllOfFile() {
  }

  public FileContentPartAllOfFile fileData(@javax.annotation.Nullable String fileData) {
    this.fileData = fileData;
    return this;
  }

  /**
   * The base64 encoded file data
   * @return fileData
   */
  @javax.annotation.Nullable
  public String getFileData() {
    return fileData;
  }

  public void setFileData(@javax.annotation.Nullable String fileData) {
    this.fileData = fileData;
  }


  public FileContentPartAllOfFile fileId(@javax.annotation.Nullable String fileId) {
    this.fileId = fileId;
    return this;
  }

  /**
   * The ID of an uploaded file to use as input
   * @return fileId
   */
  @javax.annotation.Nullable
  public String getFileId() {
    return fileId;
  }

  public void setFileId(@javax.annotation.Nullable String fileId) {
    this.fileId = fileId;
  }


  public FileContentPartAllOfFile filename(@javax.annotation.Nullable String filename) {
    this.filename = filename;
    return this;
  }

  /**
   * The name of the file, used when passing the file to the model as a string
   * @return filename
   */
  @javax.annotation.Nullable
  public String getFilename() {
    return filename;
  }

  public void setFilename(@javax.annotation.Nullable String filename) {
    this.filename = filename;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileContentPartAllOfFile fileContentPartAllOfFile = (FileContentPartAllOfFile) o;
    return Objects.equals(this.fileData, fileContentPartAllOfFile.fileData) &&
        Objects.equals(this.fileId, fileContentPartAllOfFile.fileId) &&
        Objects.equals(this.filename, fileContentPartAllOfFile.filename);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileData, fileId, filename);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileContentPartAllOfFile {\n");
    sb.append("    fileData: ").append(toIndentedString(fileData)).append("\n");
    sb.append("    fileId: ").append(toIndentedString(fileId)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("file_data", "file_id", "filename"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FileContentPartAllOfFile
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FileContentPartAllOfFile.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in FileContentPartAllOfFile is not found in the empty JSON string", FileContentPartAllOfFile.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FileContentPartAllOfFile.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `FileContentPartAllOfFile` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("file_data") != null && !jsonObj.get("file_data").isJsonNull()) && !jsonObj.get("file_data").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `file_data` to be a primitive type in the JSON string but got `%s`", jsonObj.get("file_data").toString()));
      }
      if ((jsonObj.get("file_id") != null && !jsonObj.get("file_id").isJsonNull()) && !jsonObj.get("file_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `file_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("file_id").toString()));
      }
      if ((jsonObj.get("filename") != null && !jsonObj.get("filename").isJsonNull()) && !jsonObj.get("filename").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `filename` to be a primitive type in the JSON string but got `%s`", jsonObj.get("filename").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FileContentPartAllOfFile.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FileContentPartAllOfFile' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FileContentPartAllOfFile> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FileContentPartAllOfFile.class));

       return (TypeAdapter<T>) new TypeAdapter<FileContentPartAllOfFile>() {
           @Override
           public void write(JsonWriter out, FileContentPartAllOfFile value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FileContentPartAllOfFile read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FileContentPartAllOfFile given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FileContentPartAllOfFile
   * @throws IOException if the JSON string is invalid with respect to FileContentPartAllOfFile
   */
  public static FileContentPartAllOfFile fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FileContentPartAllOfFile.class);
  }

  /**
   * Convert an instance of FileContentPartAllOfFile to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

