/*
 * HuggingFace Inference Provider API
 * Client for Hugging Face Chat Completions, Feature Extraction, and Text to Image APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mzattera.hfinferenceapi.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import javax.xml.bind.annotation.*;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import io.github.mzattera.hfinferenceapi.JSON;

/**
 * ImageGenerationResponseDataInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-14T23:10:40.473939700+01:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
@XmlRootElement(name = "ImageGenerationResponseDataInner")
@XmlAccessorType(XmlAccessType.FIELD)

public class ImageGenerationResponseDataInner {
  public static final String SERIALIZED_NAME_B64_JSON = "b64_json";
  @XmlElement(name = "b64_json")
  @SerializedName(SERIALIZED_NAME_B64_JSON)
  @javax.annotation.Nullable
  private String b64Json;

  public ImageGenerationResponseDataInner() {
  }

  public ImageGenerationResponseDataInner b64Json(@javax.annotation.Nullable String b64Json) {
    this.b64Json = b64Json;
    return this;
  }

  /**
   * Image encoded as Base64.
   * @return b64Json
   */
  @javax.annotation.Nullable
  public String getB64Json() {
    return b64Json;
  }

  public void setB64Json(@javax.annotation.Nullable String b64Json) {
    this.b64Json = b64Json;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImageGenerationResponseDataInner imageGenerationResponseDataInner = (ImageGenerationResponseDataInner) o;
    return Objects.equals(this.b64Json, imageGenerationResponseDataInner.b64Json);
  }

  @Override
  public int hashCode() {
    return Objects.hash(b64Json);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImageGenerationResponseDataInner {\n");
    sb.append("    b64Json: ").append(toIndentedString(b64Json)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("b64_json"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ImageGenerationResponseDataInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ImageGenerationResponseDataInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in ImageGenerationResponseDataInner is not found in the empty JSON string", ImageGenerationResponseDataInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ImageGenerationResponseDataInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ImageGenerationResponseDataInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("b64_json") != null && !jsonObj.get("b64_json").isJsonNull()) && !jsonObj.get("b64_json").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `b64_json` to be a primitive type in the JSON string but got `%s`", jsonObj.get("b64_json").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ImageGenerationResponseDataInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ImageGenerationResponseDataInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ImageGenerationResponseDataInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ImageGenerationResponseDataInner.class));

       return (TypeAdapter<T>) new TypeAdapter<ImageGenerationResponseDataInner>() {
           @Override
           public void write(JsonWriter out, ImageGenerationResponseDataInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ImageGenerationResponseDataInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ImageGenerationResponseDataInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ImageGenerationResponseDataInner
   * @throws IOException if the JSON string is invalid with respect to ImageGenerationResponseDataInner
   */
  public static ImageGenerationResponseDataInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ImageGenerationResponseDataInner.class);
  }

  /**
   * Convert an instance of ImageGenerationResponseDataInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

