/*
 * HuggingFace Inference Provider API
 * Client for Hugging Face Chat Completions, Feature Extraction, and Text to Image APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mzattera.hfinferenceapi.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import javax.xml.bind.annotation.*;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import io.github.mzattera.hfinferenceapi.JSON;

/**
 * Payload used to filter, sort, and paginate model results.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-08T14:41:27.970371600+01:00[Europe/Rome]", comments = "Generator version: 7.17.0")
@XmlRootElement(name = "ModelSearchRequest")
@XmlAccessorType(XmlAccessType.FIELD)

public class ModelSearchRequest {
  public static final String SERIALIZED_NAME_SEARCH = "search";
  @XmlElement(name = "search")
  @SerializedName(SERIALIZED_NAME_SEARCH)
  @javax.annotation.Nullable
  private String search;

  public static final String SERIALIZED_NAME_AUTHOR = "author";
  @XmlElement(name = "author")
  @SerializedName(SERIALIZED_NAME_AUTHOR)
  @javax.annotation.Nullable
  private String author;

  public static final String SERIALIZED_NAME_FILTER = "filter";
  @XmlElement(name = "filter")
  @SerializedName(SERIALIZED_NAME_FILTER)
  @javax.annotation.Nullable
  private String filter;

  public static final String SERIALIZED_NAME_SORT = "sort";
  @XmlElement(name = "sort")
  @SerializedName(SERIALIZED_NAME_SORT)
  @javax.annotation.Nullable
  private String sort;

  public static final String SERIALIZED_NAME_DIRECTION = "direction";
  @XmlElement(name = "direction")
  @SerializedName(SERIALIZED_NAME_DIRECTION)
  @javax.annotation.Nullable
  private Integer direction = 1;

  public static final String SERIALIZED_NAME_LIMIT = "limit";
  @XmlElement(name = "limit")
  @SerializedName(SERIALIZED_NAME_LIMIT)
  @javax.annotation.Nullable
  private Integer limit;

  public static final String SERIALIZED_NAME_FULL = "full";
  @XmlElement(name = "full")
  @SerializedName(SERIALIZED_NAME_FULL)
  @javax.annotation.Nullable
  private Boolean full = false;

  public static final String SERIALIZED_NAME_CONFIG = "config";
  @XmlElement(name = "config")
  @SerializedName(SERIALIZED_NAME_CONFIG)
  @javax.annotation.Nullable
  private Boolean config = false;

  public ModelSearchRequest() {
  }

  public ModelSearchRequest search(@javax.annotation.Nullable String search) {
    this.search = search;
    return this;
  }

  /**
   * Filter based on substrings for repos and their usernames (e.g., &#39;resnet&#39;).
   * @return search
   */
  @javax.annotation.Nullable
  public String getSearch() {
    return search;
  }

  public void setSearch(@javax.annotation.Nullable String search) {
    this.search = search;
  }


  public ModelSearchRequest author(@javax.annotation.Nullable String author) {
    this.author = author;
    return this;
  }

  /**
   * Filter models by an author or organization (e.g., &#39;huggingface&#39;).
   * @return author
   */
  @javax.annotation.Nullable
  public String getAuthor() {
    return author;
  }

  public void setAuthor(@javax.annotation.Nullable String author) {
    this.author = author;
  }


  public ModelSearchRequest filter(@javax.annotation.Nullable String filter) {
    this.filter = filter;
    return this;
  }

  /**
   * Filter based on tags (e.g., &#39;text-classification&#39;).
   * @return filter
   */
  @javax.annotation.Nullable
  public String getFilter() {
    return filter;
  }

  public void setFilter(@javax.annotation.Nullable String filter) {
    this.filter = filter;
  }


  public ModelSearchRequest sort(@javax.annotation.Nullable String sort) {
    this.sort = sort;
    return this;
  }

  /**
   * Property to use when sorting (e.g., &#39;downloads&#39; or &#39;author&#39;).
   * @return sort
   */
  @javax.annotation.Nullable
  public String getSort() {
    return sort;
  }

  public void setSort(@javax.annotation.Nullable String sort) {
    this.sort = sort;
  }


  public ModelSearchRequest direction(@javax.annotation.Nullable Integer direction) {
    this.direction = direction;
    return this;
  }

  /**
   * Direction in which to sort. Use -1 for descending, and 1 for ascending.
   * @return direction
   */
  @javax.annotation.Nullable
  public Integer getDirection() {
    return direction;
  }

  public void setDirection(@javax.annotation.Nullable Integer direction) {
    this.direction = direction;
  }


  public ModelSearchRequest limit(@javax.annotation.Nullable Integer limit) {
    this.limit = limit;
    return this;
  }

  /**
   * Limit the number of models fetched.
   * @return limit
   */
  @javax.annotation.Nullable
  public Integer getLimit() {
    return limit;
  }

  public void setLimit(@javax.annotation.Nullable Integer limit) {
    this.limit = limit;
  }


  public ModelSearchRequest full(@javax.annotation.Nullable Boolean full) {
    this.full = full;
    return this;
  }

  /**
   * Whether to fetch most model data, such as all tags, the files, etc.
   * @return full
   */
  @javax.annotation.Nullable
  public Boolean getFull() {
    return full;
  }

  public void setFull(@javax.annotation.Nullable Boolean full) {
    this.full = full;
  }


  public ModelSearchRequest config(@javax.annotation.Nullable Boolean config) {
    this.config = config;
    return this;
  }

  /**
   * Whether to also fetch the repo config.
   * @return config
   */
  @javax.annotation.Nullable
  public Boolean getConfig() {
    return config;
  }

  public void setConfig(@javax.annotation.Nullable Boolean config) {
    this.config = config;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelSearchRequest modelSearchRequest = (ModelSearchRequest) o;
    return Objects.equals(this.search, modelSearchRequest.search) &&
        Objects.equals(this.author, modelSearchRequest.author) &&
        Objects.equals(this.filter, modelSearchRequest.filter) &&
        Objects.equals(this.sort, modelSearchRequest.sort) &&
        Objects.equals(this.direction, modelSearchRequest.direction) &&
        Objects.equals(this.limit, modelSearchRequest.limit) &&
        Objects.equals(this.full, modelSearchRequest.full) &&
        Objects.equals(this.config, modelSearchRequest.config);
  }

  @Override
  public int hashCode() {
    return Objects.hash(search, author, filter, sort, direction, limit, full, config);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelSearchRequest {\n");
    sb.append("    search: ").append(toIndentedString(search)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    filter: ").append(toIndentedString(filter)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    full: ").append(toIndentedString(full)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("search", "author", "filter", "sort", "direction", "limit", "full", "config"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ModelSearchRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ModelSearchRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in ModelSearchRequest is not found in the empty JSON string", ModelSearchRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ModelSearchRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ModelSearchRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("search") != null && !jsonObj.get("search").isJsonNull()) && !jsonObj.get("search").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `search` to be a primitive type in the JSON string but got `%s`", jsonObj.get("search").toString()));
      }
      if ((jsonObj.get("author") != null && !jsonObj.get("author").isJsonNull()) && !jsonObj.get("author").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `author` to be a primitive type in the JSON string but got `%s`", jsonObj.get("author").toString()));
      }
      if ((jsonObj.get("filter") != null && !jsonObj.get("filter").isJsonNull()) && !jsonObj.get("filter").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `filter` to be a primitive type in the JSON string but got `%s`", jsonObj.get("filter").toString()));
      }
      if ((jsonObj.get("sort") != null && !jsonObj.get("sort").isJsonNull()) && !jsonObj.get("sort").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `sort` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sort").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ModelSearchRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ModelSearchRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ModelSearchRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ModelSearchRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ModelSearchRequest>() {
           @Override
           public void write(JsonWriter out, ModelSearchRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ModelSearchRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ModelSearchRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ModelSearchRequest
   * @throws IOException if the JSON string is invalid with respect to ModelSearchRequest
   */
  public static ModelSearchRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ModelSearchRequest.class);
  }

  /**
   * Convert an instance of ModelSearchRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

