/*
 * HuggingFace Inference Provider API
 * API for GenAI services: image generation, chat completions, embeddings
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mzattera.hfinferenceapi.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import javax.xml.bind.annotation.*;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import io.github.mzattera.hfinferenceapi.JSON;

/**
 * UsageCompletionTokensDetails
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-04T08:01:40.423980900+01:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
@XmlRootElement(name = "UsageCompletionTokensDetails")
@XmlAccessorType(XmlAccessType.FIELD)

public class UsageCompletionTokensDetails {
  public static final String SERIALIZED_NAME_REASONING_TOKENS = "reasoning_tokens";
  @XmlElement(name = "reasoning_tokens")
  @SerializedName(SERIALIZED_NAME_REASONING_TOKENS)
  @javax.annotation.Nullable
  private Integer reasoningTokens;

  public UsageCompletionTokensDetails() {
  }

  public UsageCompletionTokensDetails reasoningTokens(@javax.annotation.Nullable Integer reasoningTokens) {
    this.reasoningTokens = reasoningTokens;
    return this;
  }

  /**
   * Get reasoningTokens
   * @return reasoningTokens
   */
  @javax.annotation.Nullable
  public Integer getReasoningTokens() {
    return reasoningTokens;
  }

  public void setReasoningTokens(@javax.annotation.Nullable Integer reasoningTokens) {
    this.reasoningTokens = reasoningTokens;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsageCompletionTokensDetails usageCompletionTokensDetails = (UsageCompletionTokensDetails) o;
    return Objects.equals(this.reasoningTokens, usageCompletionTokensDetails.reasoningTokens);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reasoningTokens);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsageCompletionTokensDetails {\n");
    sb.append("    reasoningTokens: ").append(toIndentedString(reasoningTokens)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("reasoning_tokens"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UsageCompletionTokensDetails
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UsageCompletionTokensDetails.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in UsageCompletionTokensDetails is not found in the empty JSON string", UsageCompletionTokensDetails.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UsageCompletionTokensDetails.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `UsageCompletionTokensDetails` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UsageCompletionTokensDetails.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UsageCompletionTokensDetails' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UsageCompletionTokensDetails> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UsageCompletionTokensDetails.class));

       return (TypeAdapter<T>) new TypeAdapter<UsageCompletionTokensDetails>() {
           @Override
           public void write(JsonWriter out, UsageCompletionTokensDetails value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UsageCompletionTokensDetails read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UsageCompletionTokensDetails given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UsageCompletionTokensDetails
   * @throws IOException if the JSON string is invalid with respect to UsageCompletionTokensDetails
   */
  public static UsageCompletionTokensDetails fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UsageCompletionTokensDetails.class);
  }

  /**
   * Convert an instance of UsageCompletionTokensDetails to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

