/*
 * HuggingFace Inference Provider API
 * Client for Hugging Face Chat Completions, Feature Extraction, and Text to Image APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mzattera.hfinferenceapi.client.model;

import io.github.mzattera.hfinferenceapi.client.model.MessageContentPart;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AssistantMessageAllOfContent
 */
public class AssistantMessageAllOfContentTest {
    private final AssistantMessageAllOfContent model = new AssistantMessageAllOfContent();

    /**
     * Model tests for AssistantMessageAllOfContent
     */
    @Test
    public void testAssistantMessageAllOfContent() {
        // TODO: test AssistantMessageAllOfContent
    }

}
