/*
 * HuggingFace Inference Provider API
 * Client for Hugging Face Chat Completions, Feature Extraction, and Text to Image APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mzattera.hfinferenceapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.mzattera.hfinferenceapi.client.model.AssistantMessageAllOfContent;
import io.github.mzattera.hfinferenceapi.client.model.Message;
import java.io.IOException;
import java.util.Arrays;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AssistantMessage
 */
public class AssistantMessageTest {
    private final AssistantMessage model = new AssistantMessage();

    /**
     * Model tests for AssistantMessage
     */
    @Test
    public void testAssistantMessage() {
        // TODO: test AssistantMessage
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
