/*
 * HuggingFace Inference Provider API
 * API for GenAI services: image generation, chat completions, embeddings
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mzattera.hfinferenceapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.mzattera.hfinferenceapi.client.model.ChatCompletionRequestToolChoiceOneOfFunction;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ChatCompletionRequestToolChoiceOneOf
 */
public class ChatCompletionRequestToolChoiceOneOfTest {
    private final ChatCompletionRequestToolChoiceOneOf model = new ChatCompletionRequestToolChoiceOneOf();

    /**
     * Model tests for ChatCompletionRequestToolChoiceOneOf
     */
    @Test
    public void testChatCompletionRequestToolChoiceOneOf() {
        // TODO: test ChatCompletionRequestToolChoiceOneOf
    }

    /**
     * Test the property 'function'
     */
    @Test
    public void functionTest() {
        // TODO: test function
    }

}
