/*
 * HuggingFace Inference Provider API
 * API for GenAI services: image generation, chat completions, embeddings
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mzattera.hfinferenceapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EmbeddingsRequest
 */
public class EmbeddingsRequestTest {
    private final EmbeddingsRequest model = new EmbeddingsRequest();

    /**
     * Model tests for EmbeddingsRequest
     */
    @Test
    public void testEmbeddingsRequest() {
        // TODO: test EmbeddingsRequest
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'input'
     */
    @Test
    public void inputTest() {
        // TODO: test input
    }

    /**
     * Test the property 'normalize'
     */
    @Test
    public void normalizeTest() {
        // TODO: test normalize
    }

    /**
     * Test the property 'promptName'
     */
    @Test
    public void promptNameTest() {
        // TODO: test promptName
    }

    /**
     * Test the property 'truncate'
     */
    @Test
    public void truncateTest() {
        // TODO: test truncate
    }

    /**
     * Test the property 'truncationDirection'
     */
    @Test
    public void truncationDirectionTest() {
        // TODO: test truncationDirection
    }

}
