/*
 * HuggingFace Inference Provider API
 * API for GenAI services: image generation, chat completions, embeddings
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mzattera.hfinferenceapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ImageGenerationRequestParameters
 */
public class ImageGenerationRequestParametersTest {
    private final ImageGenerationRequestParameters model = new ImageGenerationRequestParameters();

    /**
     * Model tests for ImageGenerationRequestParameters
     */
    @Test
    public void testImageGenerationRequestParameters() {
        // TODO: test ImageGenerationRequestParameters
    }

    /**
     * Test the property 'guidanceScale'
     */
    @Test
    public void guidanceScaleTest() {
        // TODO: test guidanceScale
    }

    /**
     * Test the property 'negativePrompt'
     */
    @Test
    public void negativePromptTest() {
        // TODO: test negativePrompt
    }

    /**
     * Test the property 'numInferenceSteps'
     */
    @Test
    public void numInferenceStepsTest() {
        // TODO: test numInferenceSteps
    }

    /**
     * Test the property 'width'
     */
    @Test
    public void widthTest() {
        // TODO: test width
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'scheduler'
     */
    @Test
    public void schedulerTest() {
        // TODO: test scheduler
    }

    /**
     * Test the property 'seed'
     */
    @Test
    public void seedTest() {
        // TODO: test seed
    }

}
