/*
 * HuggingFace Inference Provider API
 * Client for Hugging Face Chat Completions, Feature Extraction, and Text to Image APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mzattera.hfinferenceapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TokenLogProbTopLogprobsInner
 */
public class TokenLogProbTopLogprobsInnerTest {
    private final TokenLogProbTopLogprobsInner model = new TokenLogProbTopLogprobsInner();

    /**
     * Model tests for TokenLogProbTopLogprobsInner
     */
    @Test
    public void testTokenLogProbTopLogprobsInner() {
        // TODO: test TokenLogProbTopLogprobsInner
    }

    /**
     * Test the property 'logprob'
     */
    @Test
    public void logprobTest() {
        // TODO: test logprob
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

}
