/*
 * HuggingFace Inference Provider API
 * API for GenAI services: image generation, chat completions, embeddings
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mzattera.hfinferenceapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.mzattera.hfinferenceapi.client.model.UsageCompletionTokensDetails;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Usage
 */
public class UsageTest {
    private final Usage model = new Usage();

    /**
     * Model tests for Usage
     */
    @Test
    public void testUsage() {
        // TODO: test Usage
    }

    /**
     * Test the property 'completionTokens'
     */
    @Test
    public void completionTokensTest() {
        // TODO: test completionTokens
    }

    /**
     * Test the property 'completionTime'
     */
    @Test
    public void completionTimeTest() {
        // TODO: test completionTime
    }

    /**
     * Test the property 'completionTokensDetails'
     */
    @Test
    public void completionTokensDetailsTest() {
        // TODO: test completionTokensDetails
    }

    /**
     * Test the property 'promptTokens'
     */
    @Test
    public void promptTokensTest() {
        // TODO: test promptTokens
    }

    /**
     * Test the property 'promptTime'
     */
    @Test
    public void promptTimeTest() {
        // TODO: test promptTime
    }

    /**
     * Test the property 'promptTokensDetails'
     */
    @Test
    public void promptTokensDetailsTest() {
        // TODO: test promptTokensDetails
    }

    /**
     * Test the property 'totalTokens'
     */
    @Test
    public void totalTokensTest() {
        // TODO: test totalTokens
    }

    /**
     * Test the property 'totalTime'
     */
    @Test
    public void totalTimeTest() {
        // TODO: test totalTime
    }

    /**
     * Test the property 'queueTime'
     */
    @Test
    public void queueTimeTest() {
        // TODO: test queueTime
    }

}
