/*
 * HuggingFace Inference Provider API
 * Client for Hugging Face Chat Completions, Feature Extraction, and Text to Image APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mzattera.hfinferenceapi;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonElement;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.TypeSelector;

import okio.ByteString;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.nio.charset.StandardCharsets;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.Map;
import java.util.HashMap;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
                .registerTypeSelector(io.github.mzattera.hfinferenceapi.client.model.AssistantMessage.class, new TypeSelector<io.github.mzattera.hfinferenceapi.client.model.AssistantMessage>() {
                    @Override
                    public Class<? extends io.github.mzattera.hfinferenceapi.client.model.AssistantMessage> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("AssistantMessage", io.github.mzattera.hfinferenceapi.client.model.AssistantMessage.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "role"));
                    }
          })
                .registerTypeSelector(io.github.mzattera.hfinferenceapi.client.model.AudioContentPart.class, new TypeSelector<io.github.mzattera.hfinferenceapi.client.model.AudioContentPart>() {
                    @Override
                    public Class<? extends io.github.mzattera.hfinferenceapi.client.model.AudioContentPart> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("AudioContentPart", io.github.mzattera.hfinferenceapi.client.model.AudioContentPart.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "type"));
                    }
          })
                .registerTypeSelector(io.github.mzattera.hfinferenceapi.client.model.DeveloperMessage.class, new TypeSelector<io.github.mzattera.hfinferenceapi.client.model.DeveloperMessage>() {
                    @Override
                    public Class<? extends io.github.mzattera.hfinferenceapi.client.model.DeveloperMessage> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("DeveloperMessage", io.github.mzattera.hfinferenceapi.client.model.DeveloperMessage.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "role"));
                    }
          })
                .registerTypeSelector(io.github.mzattera.hfinferenceapi.client.model.FileContentPart.class, new TypeSelector<io.github.mzattera.hfinferenceapi.client.model.FileContentPart>() {
                    @Override
                    public Class<? extends io.github.mzattera.hfinferenceapi.client.model.FileContentPart> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("FileContentPart", io.github.mzattera.hfinferenceapi.client.model.FileContentPart.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "type"));
                    }
          })
                .registerTypeSelector(io.github.mzattera.hfinferenceapi.client.model.FunctionTool.class, new TypeSelector<io.github.mzattera.hfinferenceapi.client.model.FunctionTool>() {
                    @Override
                    public Class<? extends io.github.mzattera.hfinferenceapi.client.model.FunctionTool> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("FunctionTool", io.github.mzattera.hfinferenceapi.client.model.FunctionTool.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "type"));
                    }
          })
                .registerTypeSelector(io.github.mzattera.hfinferenceapi.client.model.FunctionToolCall.class, new TypeSelector<io.github.mzattera.hfinferenceapi.client.model.FunctionToolCall>() {
                    @Override
                    public Class<? extends io.github.mzattera.hfinferenceapi.client.model.FunctionToolCall> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("FunctionToolCall", io.github.mzattera.hfinferenceapi.client.model.FunctionToolCall.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "type"));
                    }
          })
                .registerTypeSelector(io.github.mzattera.hfinferenceapi.client.model.ImageContentPart.class, new TypeSelector<io.github.mzattera.hfinferenceapi.client.model.ImageContentPart>() {
                    @Override
                    public Class<? extends io.github.mzattera.hfinferenceapi.client.model.ImageContentPart> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("ImageContentPart", io.github.mzattera.hfinferenceapi.client.model.ImageContentPart.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "type"));
                    }
          })
                .registerTypeSelector(io.github.mzattera.hfinferenceapi.client.model.JsonResponseFormat.class, new TypeSelector<io.github.mzattera.hfinferenceapi.client.model.JsonResponseFormat>() {
                    @Override
                    public Class<? extends io.github.mzattera.hfinferenceapi.client.model.JsonResponseFormat> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("JsonResponseFormat", io.github.mzattera.hfinferenceapi.client.model.JsonResponseFormat.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "type"));
                    }
          })
                .registerTypeSelector(io.github.mzattera.hfinferenceapi.client.model.Message.class, new TypeSelector<io.github.mzattera.hfinferenceapi.client.model.Message>() {
                    @Override
                    public Class<? extends io.github.mzattera.hfinferenceapi.client.model.Message> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("assistant", io.github.mzattera.hfinferenceapi.client.model.AssistantMessage.class);
                        classByDiscriminatorValue.put("developer", io.github.mzattera.hfinferenceapi.client.model.DeveloperMessage.class);
                        classByDiscriminatorValue.put("system", io.github.mzattera.hfinferenceapi.client.model.SystemMessage.class);
                        classByDiscriminatorValue.put("user", io.github.mzattera.hfinferenceapi.client.model.UserMessage.class);
                        classByDiscriminatorValue.put("ToolMessage", io.github.mzattera.hfinferenceapi.client.model.ToolMessage.class);
                        classByDiscriminatorValue.put("Message", io.github.mzattera.hfinferenceapi.client.model.Message.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "role"));
                    }
          })
                .registerTypeSelector(io.github.mzattera.hfinferenceapi.client.model.MessageContentPart.class, new TypeSelector<io.github.mzattera.hfinferenceapi.client.model.MessageContentPart>() {
                    @Override
                    public Class<? extends io.github.mzattera.hfinferenceapi.client.model.MessageContentPart> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("file", io.github.mzattera.hfinferenceapi.client.model.FileContentPart.class);
                        classByDiscriminatorValue.put("image", io.github.mzattera.hfinferenceapi.client.model.ImageContentPart.class);
                        classByDiscriminatorValue.put("input_audio", io.github.mzattera.hfinferenceapi.client.model.AudioContentPart.class);
                        classByDiscriminatorValue.put("refusal", io.github.mzattera.hfinferenceapi.client.model.RefusalContentPart.class);
                        classByDiscriminatorValue.put("text", io.github.mzattera.hfinferenceapi.client.model.TextContentPart.class);
                        classByDiscriminatorValue.put("MessageContentPart", io.github.mzattera.hfinferenceapi.client.model.MessageContentPart.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "type"));
                    }
          })
                .registerTypeSelector(io.github.mzattera.hfinferenceapi.client.model.RefusalContentPart.class, new TypeSelector<io.github.mzattera.hfinferenceapi.client.model.RefusalContentPart>() {
                    @Override
                    public Class<? extends io.github.mzattera.hfinferenceapi.client.model.RefusalContentPart> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("RefusalContentPart", io.github.mzattera.hfinferenceapi.client.model.RefusalContentPart.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "type"));
                    }
          })
                .registerTypeSelector(io.github.mzattera.hfinferenceapi.client.model.ResponseFormat.class, new TypeSelector<io.github.mzattera.hfinferenceapi.client.model.ResponseFormat>() {
                    @Override
                    public Class<? extends io.github.mzattera.hfinferenceapi.client.model.ResponseFormat> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("json_object", io.github.mzattera.hfinferenceapi.client.model.JsonResponseFormat.class);
                        classByDiscriminatorValue.put("json_schema", io.github.mzattera.hfinferenceapi.client.model.SchemaResponseFormat.class);
                        classByDiscriminatorValue.put("text", io.github.mzattera.hfinferenceapi.client.model.TextResponseFormat.class);
                        classByDiscriminatorValue.put("ResponseFormat", io.github.mzattera.hfinferenceapi.client.model.ResponseFormat.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "type"));
                    }
          })
                .registerTypeSelector(io.github.mzattera.hfinferenceapi.client.model.SchemaResponseFormat.class, new TypeSelector<io.github.mzattera.hfinferenceapi.client.model.SchemaResponseFormat>() {
                    @Override
                    public Class<? extends io.github.mzattera.hfinferenceapi.client.model.SchemaResponseFormat> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("SchemaResponseFormat", io.github.mzattera.hfinferenceapi.client.model.SchemaResponseFormat.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "type"));
                    }
          })
                .registerTypeSelector(io.github.mzattera.hfinferenceapi.client.model.SystemMessage.class, new TypeSelector<io.github.mzattera.hfinferenceapi.client.model.SystemMessage>() {
                    @Override
                    public Class<? extends io.github.mzattera.hfinferenceapi.client.model.SystemMessage> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("SystemMessage", io.github.mzattera.hfinferenceapi.client.model.SystemMessage.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "role"));
                    }
          })
                .registerTypeSelector(io.github.mzattera.hfinferenceapi.client.model.TextContentPart.class, new TypeSelector<io.github.mzattera.hfinferenceapi.client.model.TextContentPart>() {
                    @Override
                    public Class<? extends io.github.mzattera.hfinferenceapi.client.model.TextContentPart> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("TextContentPart", io.github.mzattera.hfinferenceapi.client.model.TextContentPart.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "type"));
                    }
          })
                .registerTypeSelector(io.github.mzattera.hfinferenceapi.client.model.TextResponseFormat.class, new TypeSelector<io.github.mzattera.hfinferenceapi.client.model.TextResponseFormat>() {
                    @Override
                    public Class<? extends io.github.mzattera.hfinferenceapi.client.model.TextResponseFormat> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("TextResponseFormat", io.github.mzattera.hfinferenceapi.client.model.TextResponseFormat.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "type"));
                    }
          })
                .registerTypeSelector(io.github.mzattera.hfinferenceapi.client.model.Tool.class, new TypeSelector<io.github.mzattera.hfinferenceapi.client.model.Tool>() {
                    @Override
                    public Class<? extends io.github.mzattera.hfinferenceapi.client.model.Tool> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("function", io.github.mzattera.hfinferenceapi.client.model.FunctionTool.class);
                        classByDiscriminatorValue.put("Tool", io.github.mzattera.hfinferenceapi.client.model.Tool.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "type"));
                    }
          })
                .registerTypeSelector(io.github.mzattera.hfinferenceapi.client.model.ToolCall.class, new TypeSelector<io.github.mzattera.hfinferenceapi.client.model.ToolCall>() {
                    @Override
                    public Class<? extends io.github.mzattera.hfinferenceapi.client.model.ToolCall> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("function", io.github.mzattera.hfinferenceapi.client.model.FunctionToolCall.class);
                        classByDiscriminatorValue.put("ToolCall", io.github.mzattera.hfinferenceapi.client.model.ToolCall.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "type"));
                    }
          })
                .registerTypeSelector(io.github.mzattera.hfinferenceapi.client.model.ToolMessage.class, new TypeSelector<io.github.mzattera.hfinferenceapi.client.model.ToolMessage>() {
                    @Override
                    public Class<? extends io.github.mzattera.hfinferenceapi.client.model.ToolMessage> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("ToolMessage", io.github.mzattera.hfinferenceapi.client.model.ToolMessage.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "role"));
                    }
          })
                .registerTypeSelector(io.github.mzattera.hfinferenceapi.client.model.UserMessage.class, new TypeSelector<io.github.mzattera.hfinferenceapi.client.model.UserMessage>() {
                    @Override
                    public Class<? extends io.github.mzattera.hfinferenceapi.client.model.UserMessage> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("UserMessage", io.github.mzattera.hfinferenceapi.client.model.UserMessage.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "role"));
                    }
          })
        ;
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    static {
        GsonBuilder gsonBuilder = createGson();
        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDate.class, localDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.AssistantMessage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.AssistantMessageAllOfAudio.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.AssistantMessageAllOfContent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.AudioContentPart.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.AudioContentPartAllOfInputAudio.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.ChatCompletionRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.ChatCompletionRequestStreamOptions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.ChatCompletionRequestToolChoice.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.ChatCompletionRequestToolChoiceOneOf.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.ChatCompletionRequestToolChoiceOneOfFunction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.ChatCompletionResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.Choice.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.DeveloperMessage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.DeveloperMessageAllOfContent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.EmbeddingData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.EmbeddingsRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.EmbeddingsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.FileContentPart.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.FileContentPartAllOfFile.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.Function.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.FunctionTool.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.FunctionToolCall.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.FunctionToolCallAllOfFunction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.ImageContentPart.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.ImageContentPartAllOfImageUrl.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.ImageGenerationRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.ImageGenerationRequestParameters.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.ImageGenerationResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.ImageGenerationResponseDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.JsonResponseFormat.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.LogProbs.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.ModelInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.ModelSearchRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.RefusalContentPart.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.SchemaResponseFormat.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.SystemMessage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.SystemMessageAllOfContent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.TextContentPart.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.TextResponseFormat.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.TokenLogProb.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.ToolMessage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.ToolMessageAllOfContent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.Usage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.UsageCompletionTokensDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.UserMessage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.github.mzattera.hfinferenceapi.client.model.UserMessageAllOfContent.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
    * Deserialize the given JSON InputStream to a Java object.
    *
    * @param <T>         Type
    * @param inputStream The JSON InputStream
    * @param returnType  The type to deserialize into
    * @return The deserialized Java object
    */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(InputStream inputStream, Type returnType) throws IOException {
        try (InputStreamReader reader = new InputStreamReader(inputStream, StandardCharsets.UTF_8)) {
        if (isLenientOnJson) {
            // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
            JsonReader jsonReader = new JsonReader(reader);
            jsonReader.setLenient(true);
            return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(reader, returnType);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length()-5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
